spring.application.name=SubFlight.API

server.port=8088

airport.api.url=http://localhost:8084/api/vq/airport
aircraft.api.url=http://localhost:8085/api/v1/aircraft
flight.api.url=http://localhost:8086/api/v1/flight
airline.api.url=http://localhost:8083/api/v1/airline
database.api.url=http://localhost:8080/api/v1/db



